image: node

before_script:
  - npm install -g yarn

pages:
  stage: deploy
  script:
  - npm run build
  - mkdir public
  - cp -r dist/* public
  artifacts:
    paths:
    - public
  only:
  - master
