image: node:latest

pages:
  stage: deploy
  script:
  - git lfs pull
  - yarn
  - NODE_ENV=production npm run build
  - cat dist/index.html
  - cp -r dist public
  artifacts:
    paths:
    - public
  only:
  - master
