image: node:latest

pages:
  stage: deploy
  before_script:
    - apk add git --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/
    # Install git-lfs
    - apk add openssl --update-cache
    - wget -qO- https://github.com/git-lfs/git-lfs/releases/download/v2.1.1/git-lfs-linux-amd64-2.1.1.tar.gz | tar xz
    - mv git-lfs-*/git-lfs /usr/bin/ && rm -rf git-lfs-* && git lfs install && git lfs pull
  script:
  - git lfs pull
  - yarn
  - NODE_ENV=production npm run build
  - cat dist/index.html
  - cp -r dist public
  artifacts:
    paths:
    - public
  only:
  - master
